petabi/structured

src/table.rs

Return Option instead of Result.

---

src/parse.rs

Mentions [remake #99](https://gitlab.com/resolutions/resolutions/issues/99#note_248491303)

use default value when enum map is not provided

---

CHANGELOG.md
Cargo.toml
src/parse.rs
src/table.rs

Limit enum dimensions by users, coverage, and maximum

---

src/parse.rs
src/table.rs

store all enum values and their counts

---

CREDITS
src/bitmap.rs
src/buffer.rs
src/lib.rs
src/memory.rs
src/util.rs
src/util/bit_util.rs

This will be used to label each cell in `Column` null or not-null.

Import `Bitmap` from Apache Arrow to mark null elements in `Column`

---

src/datatypes.rs
src/parse.rs
src/table.rs

The former is compatible with Apache Arrow.

Use UInt32 for Enum

---

src/lib.rs
src/table.rs

work with new types of datetime and ipaddr when describing

---

src/table.rs

Use indices of clusters instead of copying the entire table for describing

---

Cargo.toml
src/table.rs

Required for REconverge to deserialize user configuration.

let ColumnType enabled with EnumString

---

CHANGELOG.md
src/lib.rs
src/table.rs

Users can set these values from frontend.

Receive time intervals and top N numbers as arguments

---

CHANGELOG.md
src/lib.rs
src/stats.rs
src/table.rs

`Table::statistics` returns time series as well.

Add `count_group_by`, a function counting values of grouped rows

---

src/lib.rs

make structs related with GroupCount pub

---

CHANGELOG.md
Cargo.toml
src/csv.rs
src/csv/reader.rs
src/lib.rs
src/stats.rs
src/table.rs

<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

remove ConcurrentEnumMap, ConcurrentReverseEnumMap

---

CHANGELOG.md
src/stats.rs
src/table.rs

Use an empty `Vec` instead of `None`.

Remove needless `Option`

---

CHANGELOG.md
Cargo.toml

Add "js" feature to support Wasm

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/table.rs
src/token.rs

add column token related things

---

src/table.rs
src/token.rs

read raw event fields for label

---

src/csv/reader.rs
src/stats.rs
src/table.rs

`PartialEq` is required in yew 19.

Make most of statistics items derive PartialEq

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md

Update arrow to version 12

---

.github/workflows/ci.yml

change codecov branch name from `@master` to `@v2`

Change codecov branch name in ci.yml

---

Cargo.toml

Security fix according to [RUSTSEC-2020-0071](https://rustsec.org/advisories/RUSTSEC-2020-0071)

Disable default features of chrono for security

---

CHANGELOG.md
Cargo.toml
src/stats.rs
src/table.rs

Use ordered float with precision for top_n_f64 statistics

---

.github/workflows/ci.yml
CHANGELOG.md
src/table.rs

* Add function to return the `Schema` of `Table`
* Update Rust version to 1.70.0 in `Ci.yml`

Add function to return the Schema of Table
